### ISSUE TITLE
iso(G,H) is not compatible with SimpleDigraphs?

### ISSUE THREAD

**Issue by cobnett3** [scheinerman/SimpleGraphAlgorithms.jl#1]
Hi!, Thank you for making your libraries available!

I want to check the isomorphism of two **directed** graphs.
However, `SimpleGraphAlgorithms.iso2(G::SimpleGraph, H::SimpleGraph)` obviously does not accept `SimpleGraphs.SimpleDigraph` objects.

For solving the type checking issue, it is easy to fix this by defining `iso2di(G::SimpleDigraph, H::SimpleDigraph)`. But I'm not sure the substantial content of this function `iso2` is still valid for directed graphs.

**Comment by scheinerman** [comment]
Thanks for writing. I don’t really have the time/energy to work on an isomorphism checker for directed graphs at this time. I don’t think my algorithms are all that good either. They essentially rely on a generic IP solver and I’m sure the experts in this area know much better techniques. It would be amazing if someone could port Nauty to Julia for example.

On Oct 19, 2016, at 00:03, tsuga <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi!, Thank you for making your libraries available!

I want to check the isomorphism of two directed graphs.
However, SimpleGraphAlgorithms.iso2(G::SimpleGraph, H::SimpleGraph) obviously does not accept SimpleGraphs.SimpleDigraph objects.

For solving the type checking issue, it is easy to fix this by defining iso2di(G::SimpleDigraph, H::SimpleDigraph). But I'm not sure the substantial content of this function iso2 is still valid for directed graphs.
