### ISSUE TITLE
Switch to Graphs instead of SimpleGraphs

### ISSUE THREAD

**Issue by newptcai** [scheinerman/SimpleGraphAlgorithms.jl#10]
Can this module switch to use `Graphs` instead of `SimpleGraphs`? I think the latter's development has been replaced by the former.

**Comment by scheinerman** [comment]
Hi @newptcai ,

Alas, that would take a lot of work and I've created my own "ecosystem" of graph tools (that predate `LightGraphs` and its successor, `Graphs`. 

What you can do is use a tool I provide to convert a `Graphs.SimpleGraph` to my `SimpleGraphs.UndirectedGraph`. The files and documentation are [here](https://github.com/scheinerman/SimpleGraphs.jl/tree/master/extras).

I hope this helps.

**Comment by newptcai** [comment]
Yes. That works. Thanks. 

Though it would be nice to have a separate package containing these conversion functions.

**Comment by scheinerman** [comment]
Hello @newptcai : Per your suggestion, I have created a [`SimpleGraphConverter`](https://github.com/scheinerman/SimpleGraphConverter.jl) module to facilitate conversion between graphs defined in my `SimpleGraphs` and those in Julia's `Graphs` module.  Please check it out and let me know if it helps.

**Comment by newptcai** [comment]
@scheinerman Yes it helps. I use `Graphs` for generating random graphs and some algorithms in `SimpleGraphs` when I teach discrete math. Being able to use both is really great. Thank you!
