### ISSUE TITLE
Problem with definition of `getindex`

### ISSUE THREAD

**Issue by mschauer** [scheinerman/SimpleGraphAlgorithms.jl#5]
The definition below creates a "type piracy" problem, see https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-type-piracy for a short explanation why this is the case.

https://github.com/scheinerman/SimpleGraphAlgorithms.jl/blob/d7d5d662dda905ccdbc34299184c1b65f24fc082/src/chrome_poly.jl#L100

(similar for `setindex!`)

**Comment by scheinerman** [comment]
Hi: I'm not sure I understand. Perhaps all I need to do is to change `getindex(CPM, G)` definition so the arguments are typed, like this:`getindex(CPM::ChromePolyMemo, G::SimpleGraph)`. Would that fix the problem?

**Comment by mschauer** [comment]
Yes, exactly, that would work.

**Comment by scheinerman** [comment]
I updated this repository, but I'm having some trouble registering. I'll try again later. Thanks for your help!

**Comment by scheinerman** [comment]
New version registered. Thanks again for your help.
