### ISSUE TITLE
algorithms for weighted graphs

### ISSUE THREAD

**Issue by Edenharder** [scheinerman/SimpleGraphAlgorithms.jl#6]
Is it possible to generalize the current algorithms for the weighted graphs? For example, the weighted independence number. Is there any main obstacle? I can understand that it will need huge effort.

**Comment by scheinerman** [comment]
Hi: In principle it can be done. However, it would likely require a rebuild of my `SimpleGraphs` module to include weighted graphs, and I'm not up for that. If you need to solve a specific problem, I think the most expedient solution is to create a modified version of the code for yourself. If your graphs aren't too big, then that should work fine. For large graphs, you may need a custom approach. Good luck.

**Comment by Edenharder** [comment]
Thank you for the comment. I have never thought that it could need to rebuild `SimpleGraphs`. Since the weight is an extra parameter, is it possible to adapt the algorithm for this extra parameter/input without touching `SimpleGraphs`?

**Comment by scheinerman** [comment]
Yes, I suppose a function such as `max_indep_set` could have a two-argument version where the first argument is the graph and the second argument is a `Dict` mapping vertices to weights. I'm not really up for making that change. The "standard" `Graphs` package is probably where the investment should be made. Sorry :-(
