### ISSUE TITLE
Not compatible with Graphs.jl

### ISSUE THREAD

**Issue by dstahlke** [scheinerman/SimpleGraphAlgorithms.jl#7]
It seems like Graphs.SimpleGraph and SimpleGraphs.SimpleGraph are two different things.  Probably these functions should take AbstractGraph as the argument, though it looks like SimpleGraphs.SimpleGraph is not a subclass of AbstractGraph for some reason.

    julia> using Graphs, SimpleGraphAlgorithms
    julia> chromatic_number(complete_graph(10))
    ERROR: MethodError: no method matching chromatic_number(::SimpleGraph{Int64})
    Closest candidates are:
      chromatic_number(::SimpleGraphs.SimpleGraph) at ~/.julia/packages/SimpleGraphAlgorithms/RBOxo/src/vertex-coloring.jl:104
      chromatic_number(::SimpleGraphs.SimpleGraph, ::Bool) at ~/.julia/packages/SimpleGraphAlgorithms/RBOxo/src/vertex-coloring.jl:104

**Comment by scheinerman** [comment]
You're right. My `SimpleGraphs` and accompanying packages are separate from `Graphs`; they aren't interoperable. My `SimpleGraphs` project predates `LightGraphs` which eventually replaced `Graphs`. When that package was `LightGraphs` there were no name collisions. 

At present, the best I can offer is to use the `graph_convert` function distributed with the `SimpleGraphs` package (found in the file `graph_converter.jl` in the `extras` folder).  You can use this to convert a graph between `SimpleGraphs.SimpleGraph` and `Graphs.SimpleGraph` types.

**Comment by dstahlke** [comment]
Would you be open to a patch, if I find time in the future to convert this package over to use Graphs rather than SimpleGraphs?  Your package implements many basic and necessary algorithms that are not available in Graphs.

**Comment by scheinerman** [comment]
My initial reaction is "no". This package (and several more the rely on it) is a tool I use for my own work. Some ways of manipulating graphs have different names (e.g., I use `add!(G,v)` to add an edges, whereas `Graphs` uses `add_edge!`). I have lots of other code that relies on how I've set things up.

But: **Please tell me what you have in mind**. 

In the past, when I've accepted pull requests they have been for minor enhancements that are highly local. 

What I might consider is changing the type `SimpleGraph` to `UndirectedGraph` and provide `UG` as an abbreviation. That still would require lots of changes in several repositories (including lots of documentation changes). 

For now you could use the `graph_convert` like this:

```
$ cd .julia/dev/SimpleGraphs/extras/
homer:~/.julia/dev/SimpleGraphs/extras
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Graphs, SimpleGraphs, SimpleGraphAlgorithms

julia> g = path_graph(10)
{10, 9} undirected simple Int64 graph

julia> include("graph_converter.jl")
graph_convert (generic function with 2 methods)

julia> chromatic_number(graph_convert(g))
Welcome to the CBC MILP Solver 
# lots of lines deleted

2
```

**Comment by dstahlke** [comment]
I can try to find a way that does not cause any backwards-compatibility problems (when I find time) and run it by you.  One option would be to make SimpleGraphs.SimpleGraph subclass AbstractGraph (if the SimpleGraphs maintainers approve), and then have your functions take AbstractGraph as a parameter.  Then your functions would work with both types.  I haven't looked into the code yet to see if this route makes any sense.

**Comment by scheinerman** [comment]
Thanks, but please keep me informed before you invest too much time. I would strongly prefer that my `SimpleGraphs` (and related modules) not be dependent on `Graphs`. 

In the meantime, does using `graph_convert` enable you to do what you want?

**Comment by dstahlke** [comment]
If adding a dependency to Graphs is not permissible, then it's probably not possible to make it work because that's where AbstractGraph comes from.  I was able to call your functions using `SimpleGraphs.SimpleGraph(adjacency_matrix(g))`.  But for now I only need chromatic_number, and I was able to easily create a relatively fast implementation of that using PicoSAT.

**Comment by scheinerman** [comment]
Hello again @dstahlke : I have reworked `SimpleGraphs` and related modules so there are no longer a name clashes with `Graphs`.  I also created a way to seamlessly convert between the two types of graphs. See [this file](https://github.com/scheinerman/SimpleGraphs.jl/blob/master/extras/graph_converter.jl). So if you have a graph `g` created using `Graphs`, and you want to use some function `func` from `SimpleGraphAlgorithms`, then you can do something like this: `func(UG(g))`. Hope this helps.

**Comment by dstahlke** [comment]
Thanks.  That works and is helpful.  FYI, I have found that for graph coloring (and chromatic number), PicoSAT runs much faster than the integer programming solver.  I can send you some code if you are curious.  I'm trying to get it into Graphs.jl, but I suspect they won't want to add the extra dependency to PicoSAT.

**Comment by scheinerman** [comment]
Thanks. Yes, I'd be curious to see how it works. I'm not familiar with PicoSAT.

**Comment by dstahlke** [comment]
Here you go: https://gist.github.com/dstahlke/8e4fd40fa845e792ff7cd3f6b4ccb124

If you haven't experienced SAT solvers before, you are in for a treat.  They are basically a magic tool where you describe your problem and they just pop out the solution.  I've heard that if you have an NP complete problem and spend two weeks cooking up the most efficient solution you can think of, a SAT solver will still be faster (and will take five minutes to set up).  In my experience that's not quite true, but close enough.  PicoSAT only supports boolean expressions, which is enough in this case.  If you need integers and more complex theory you can try Z3.  But for boolean, PicoSAT seems faster.
